; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = nanoatmega328

[env]
lib_deps = fastled/FastLED@^3.10.0

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
lib_deps = fastled/FastLED@^3.10.1

build_src_filter = +<main.cpp>
	+<ESP32/*>
	+<ALUP/*>

[env:nodemcu]
platform = espressif8266
board = nodemcu
framework = arduino
monitor_speed = 115200
lib_deps = fastled/FastLED@^3.10.1

build_src_filter = +<main.cpp>
	+<ESP8266/*>
	+<ALUP/*>	
	

[env:d1_mini_tcp]
platform = espressif8266
board = d1_mini
framework = arduino
build_flags = -D CONFIG_FILE=\"configs/d1mini_tcp.h\"
monitor_speed = 115200
lib_deps = fastled/FastLED@^3.10.1

build_src_filter = +<main.cpp>
	+<ESP8266/*>
	+<ALUP/*>


	

[env:nanoatmega328]
platform = atmelavr
framework = arduino
board = nanoatmega328new
build_src_filter = +<main.cpp>
	+<ALUP/*>

lib_deps = fastled/FastLED@^3.10.1

[env:nanoatmega328_old]
platform = atmelavr
framework = arduino
board = nanoatmega328
build_src_filter = +<main.cpp>
	+<ALUP/*>
	
lib_deps = fastled/FastLED@^3.10.1
